"""
Training pipeline for PhishGuard's phishing-URL classifier.

Run directly:
    python -m src.train

Produces:
    models/phishing_model.joblib       -- best-performing trained model
    models/scaler.joblib               -- fitted StandardScaler
    models/metrics.json                -- evaluation metrics (never fabricated;
                                           generated by actually running this script)
    models/feature_importance.json     -- feature importances for explanations
    assets/*.png                       -- evaluation plots
"""

import json
import time

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    RocCurveDisplay,
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from src.config import (
    ASSETS_DIR,
    FEATURE_IMPORTANCE_PATH,
    METRICS_PATH,
    MODEL_PATH,
    MODELS_DIR,
    RANDOM_STATE,
    RAW_DATA_PATH,
    SCALER_PATH,
    TARGET_COLUMN,
    TEST_SIZE,
    URL_ONLY_FEATURES,
)


def load_data() -> pd.DataFrame:
    df = pd.read_csv(RAW_DATA_PATH)
    missing = [c for c in URL_ONLY_FEATURES + [TARGET_COLUMN] if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset is missing expected columns: {missing}")
    return df


def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    df = df[URL_ONLY_FEATURES + [TARGET_COLUMN]].copy()
    df = df.drop_duplicates()
    df = df.dropna()
    # CLASS_LABEL in the source dataset is already binary {0, 1}; guard anyway.
    df = df[df[TARGET_COLUMN].isin([0, 1])]
    return df


def evaluate_model(name, model, X_test, y_test, scale_input=True, scaler=None):
    X_eval = scaler.transform(X_test) if (scale_input and scaler is not None) else X_test
    y_pred = model.predict(X_eval)
    y_proba = model.predict_proba(X_eval)[:, 1]

    metrics = {
        "accuracy": round(accuracy_score(y_test, y_pred), 4),
        "precision": round(precision_score(y_test, y_pred), 4),
        "recall": round(recall_score(y_test, y_pred), 4),
        "f1_score": round(f1_score(y_test, y_pred), 4),
        "roc_auc": round(roc_auc_score(y_test, y_proba), 4),
    }
    print(f"[{name}] {metrics}")
    return metrics, y_pred, y_proba


def main():
    start = time.time()
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading dataset...")
    df = load_data()
    print(f"Raw shape: {df.shape}")

    df = clean_data(df)
    print(f"After cleaning (dedup/na drop): {df.shape}")
    print("Class balance:\n", df[TARGET_COLUMN].value_counts())

    X = df[URL_ONLY_FEATURES].values
    y = df[TARGET_COLUMN].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )
    print(f"Train: {X_train.shape}, Test: {X_test.shape}")

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # --- Baseline model ---
    print("\nTraining baseline: Logistic Regression")
    baseline = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)
    baseline.fit(X_train_scaled, y_train)
    baseline_metrics, _, baseline_proba = evaluate_model(
        "LogisticRegression", baseline, X_test, y_test, scaler=scaler
    )

    # --- Improved model ---
    print("\nTraining improved model: Random Forest")
    rf = RandomForestClassifier(
        n_estimators=300,
        max_depth=14,
        min_samples_leaf=2,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    # Random Forest does not need feature scaling, but we keep a consistent
    # inference path (always scale) so the serving code has one code path.
    rf.fit(X_train_scaled, y_train)
    rf_metrics, rf_pred, rf_proba = evaluate_model(
        "RandomForest", rf, X_test, y_test, scaler=scaler
    )

    # --- Pick the best model by F1 (balanced metric for a binary security task) ---
    if rf_metrics["f1_score"] >= baseline_metrics["f1_score"]:
        best_name, best_model, best_metrics, best_pred, best_proba = (
            "RandomForest", rf, rf_metrics, rf_pred, rf_proba
        )
    else:
        best_name, best_model = "LogisticRegression", baseline
        best_metrics, best_pred, best_proba = baseline_metrics, None, baseline_proba

    print(f"\nSelected best model: {best_name}")

    # --- Save artifacts ---
    joblib.dump(best_model, MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)

    all_metrics = {
        "baseline_logistic_regression": baseline_metrics,
        "random_forest": rf_metrics,
        "selected_model": best_name,
        "n_train_samples": int(X_train.shape[0]),
        "n_test_samples": int(X_test.shape[0]),
        "n_features": len(URL_ONLY_FEATURES),
        "trained_at_unix": int(time.time()),
    }
    with open(METRICS_PATH, "w") as f:
        json.dump(all_metrics, f, indent=2)

    # Feature importance (for the dashboard's "why this score" explanation)
    if best_name == "RandomForest":
        importances = best_model.feature_importances_
    else:
        importances = np.abs(best_model.coef_[0])
    importance_map = {
        feat: round(float(imp), 5)
        for feat, imp in sorted(
            zip(URL_ONLY_FEATURES, importances), key=lambda x: -x[1]
        )
    }
    with open(FEATURE_IMPORTANCE_PATH, "w") as f:
        json.dump(importance_map, f, indent=2)

    # --- Plots ---
    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay.from_predictions(
        y_test, rf_pred, display_labels=["Legitimate", "Phishing"], ax=ax, cmap="Blues"
    )
    ax.set_title(f"Confusion Matrix ({best_name})")
    fig.tight_layout()
    fig.savefig(ASSETS_DIR / "confusion_matrix.png", dpi=140)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(5, 5))
    RocCurveDisplay.from_predictions(y_test, rf_proba, ax=ax, name="Random Forest")
    RocCurveDisplay.from_predictions(y_test, baseline_proba, ax=ax, name="Logistic Regression")
    ax.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Chance")
    ax.set_title("ROC Curve: Baseline vs Improved Model")
    ax.legend()
    fig.tight_layout()
    fig.savefig(ASSETS_DIR / "roc_curve.png", dpi=140)
    plt.close(fig)

    top_feats = list(importance_map.items())[:12][::-1]
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.barh([f[0] for f in top_feats], [f[1] for f in top_feats], color="#2563eb")
    ax.set_title("Top 12 Feature Importances")
    ax.set_xlabel("Importance")
    fig.tight_layout()
    fig.savefig(ASSETS_DIR / "feature_importance.png", dpi=140)
    plt.close(fig)

    elapsed = time.time() - start
    print(f"\nDone in {elapsed:.1f}s. Artifacts saved to models/ and assets/.")
    print(json.dumps(all_metrics, indent=2))


if __name__ == "__main__":
    main()
